services:
  flight_review_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      STORAGE_PATH: /data
      FLIGHT_REVIEW_ENV: production
    volumes:
      - ./data:/data
    restart: unless-stopped
  nginx:
    build:
      context: ./nginx
      args:
        NGINX_CONF: ${NGINX_CONF:-default.conf}
    ports:
      - 80:80
    depends_on:
      - flight_review_app
    restart: unless-stopped

